import { CheckCircle, ExternalLink } from 'lucide-react';

export const CONTENT = {
  common: {
    close: 'Close',
    submitting: 'Submitting...',
    quiz_not_found: 'Quiz not found',
  },
  metadata: {
    root: {
      title: 'Create Next App',
      description: 'Generated by create next app',
    },
    auth: {
      title: 'Quiz Flow | Sign Up',
      description: 'Sign up to create and manage your quizzes with ease.',
    },
  },
  auth: {
    login: {
      header: 'Welcome back',
      subheader:
        'Sign in to continue creating quizzes, managing responses, and tracking your audience.',
    },
    sign_up: {
      header: 'Create an account',
      subheader:
        'Join QuizBuilder today and start building engaging quizzes in just a few clicks.',
    },
    forgot_password: {
      header: 'Forgot your password?',
      subheader:
        "Enter your email address below and we'll send you a link to reset your password.",
    },
    forgot_password_sent: {
      header: 'Reset email sent',
      subheader:
        'We just sent you an email with instructions to reset your password. Please check your inbox and follow the link provided.',
    },
    reset_password: {
      header: 'Reset password',
      subheader:
        'Create a new password for your account. Make sure to choose a strong and secure password.',
    },

    to_signUp: {
      text: 'Don’t have an account?',
      boldtext: 'Sign up',
    },
    to_logIn: {
      text: 'Already have an account?',
      boldtext: 'Log in',
    },
    back_to_logIn: {
      text: 'Get back to',
      boldtext: 'Log in',
    },
    form: {
      name: {
        label: 'Name',
        placeholder: 'Enter your name',
      },
      fullName: {
        label: 'Full name*',
        placeholder: 'Enter your full name',
        error: 'Please enter your full name',
      },
      email: {
        label: 'Email*',
        placeholder: 'Enter your email',
        error: 'Please enter a valid email address',
      },
      password: {
        label: 'Password*',
        placeholder: 'Create a password',
        error: 'Password must be at least 8 characters long',
      },
      confirmPassword: {
        label: 'Confirm password*',
        placeholder: 'Confirm your password',
        error: 'Passwords do not match',
      },
      button: {
        login: 'Log in ',
        signUp: 'Create account',
        google: 'Sign up with Google',
      },
      password_must: 'Password must:',
      divider_text: 'or continue with',
      forgot_password_notice:
        'If an account with that email exists, a password reset link has been\nsent to your email.',
      actions: {
        login: 'Login',
        sign_up: 'Sign Up',
        send_reset_link: 'Send Reset Link',
        change_password: 'Change password',
        continue_with_google: 'Continue with Google',
        google_alt: 'Google',
      },
    },
    contentSectionSlider: [
      {
        headers: ['Create Faster', 'Design Freely', 'Share Instantly'],
        paragraph: [
          'Build professional quizzes with an intuitive editor and publish them in just a few clicks.',
        ],
      },
      {
        headers: ['Collect Responses', 'Analyze Results', 'Gain Insights'],
        paragraph: [
          'Monitor submissions in real time and discover valuable trends with clear analytics.',
        ],
      },
      {
        headers: ['Engage Users', 'Grow Together', 'Collaborate Easily'],
        paragraph: [
          'Create public or private quizzes, invite your team, and keep everything organized in one place.',
        ],
      },
    ],
    a11y: {
      go_to_slide: (index: number) => `Go to slide ${index}`,
    },
    messages: {
      invalid_credentials: 'Invalid credentials',
      use_google_or_reset_password:
        'Use Google sign in for this account or reset your password.',
      signed_in_successfully: 'Signed in successfully.',
      unable_sign_in: 'Unable to sign in right now. Please try again.',
      no_account_for_email:
        'It seems like there is no account associated with this email address.',
      password_reset_instructions_sent:
        'Password reset instructions sent successfully.',
      unable_process_request:
        'Unable to process your request right now. Please try again.',
      reset_link_invalid_or_expired: 'Reset link is invalid or has expired.',
      password_updated_successfully: 'Password updated successfully.',
      unable_reset_password:
        'Unable to reset password right now. Please try again.',
      user_already_exists: 'User already exists',
      account_created_successfully: 'Account created successfully.',
      unable_create_account:
        'Unable to create account right now. Please try again.',
      logged_out_successfully: 'Logged out successfully.',
    },
    validation: {
      email_invalid: 'Please enter a valid email.',
      name_min: 'Name must be at least 2 characters long.',
      password_min: 'Be at least 8 characters long',
      password_letter: 'Contain at least one letter.',
      password_number: 'Contain at least one number.',
      password_special: 'Contain at least one special character.',
      reset_token_required: 'Reset token is required.',
      passwords_do_not_match: 'Passwords do not match',
    },
  },
  navigation: {
    main: {
      features: 'Features',
      how_it_works: 'How It Works',
      examples: 'Examples',
      pricing: 'Pricing',
      login: 'Log in',
      get_started_free: 'Get Started Free',
    },
    sidebar: {
      all_quizzes: 'All Quizzes',
      all_quizzes_description: 'Explore all available quizzes',
      my_quizzes: 'My Quizzes',
      my_quizzes_description: "View quizzes you've created",
      create_quiz: 'Create Quiz',
      create_quiz_description: 'Start a new quiz',
      results: 'Results',
      results_description: 'View quiz results',
      settings: 'Settings',
      settings_description: 'Manage your account settings',
      edit_quiz: 'Edit Quiz',
      edit_quiz_description: 'Edit an existing quiz',
      preview: 'Preview',
      preview_description: 'Preview a quiz',
    },
    landing: {
      product: 'Product',
      legal: 'Legal',
      contact_us: 'Contact Us',
      features: 'Features',
      quiz_examples: 'Quiz Examples',
      privacy_policy: 'Privacy Policy',
      terms_of_service: 'Terms of Service',
    },
  },
  footer: {
    subtitle: 'The easiest way to create interactive quizzes and surveys.',
    rightsReserved: 'Quiz Flow. All rights reserved.',
    email: 'quizflow@email.com',
    mailto: 'mailto:quizflow@email.com',
    // subtitle: 'Create, share and take quizzes in a modern and simple way.',
    // rightsReserved: '© Quiz Flow. All rights reserved.',
    withLove: 'Made with ❤️ by QuizFlow ',
    // email: 'support@quizflow.com',
    tagline: 'Simple to build.\n Easy to share.',
    recommendations: {
      title: 'Questions or Feedback?',
      email: 'nbulmak@gmail.com',
      commertial_text: 'This is a non-commercial portfolio project created by',
      creator: 'Nadiia Bulmak',
    },
  },
  main: {
    hero: {
      badge: 'Create. Share. Engage.',
      title_prefix: 'Create beautiful',
      title_highlight: 'quizzes',
      title_suffix: 'in minutes',
      description:
        'QuizFlow helps you build interactive quizzes, share them anywhere,\nand get insights – all in one simple platform.',
      create_first_quiz: 'Create Your First Quiz',
      try_demo_quiz: 'Try a Demo Quiz',
      no_signup_required: 'No signup required to take quizzes',
      works_on_any_device: 'Works on any device',
      free_to_start: '100% Free to start',
    },
    features: {
      eyebrow: 'Features',
      title: 'Everything you need to create amazing quizzes',
      items: [
        {
          title: 'Easy Quiz Builder',
          description:
            'Create quizzes with multiple choice questions in a clean and intuitive interface.',
        },
        {
          title: 'Share Instantly',
          description:
            'Get a public link and share your quiz anywhere. No login required for takers.',
        },
        {
          title: 'Engaging Experience',
          description:
            'Beautiful, mobile-friendly quiz experience that keeps your audience engaged.',
        },
        {
          title: 'View Results',
          description:
            'See how your quiz is performing with insights and detailed results.',
        },
      ],
    },
    how_it_works: {
      eyebrow: 'How It Works',
      title: 'Create and share your quiz in 3 simple steps',
      steps: [
        {
          number: '1',
          title: 'Create',
          description: 'Build your quiz with questions and answer options.',
        },
        {
          number: '2',
          title: 'Share',
          description: 'Publish and get your unique quiz link.',
        },
        {
          number: '3',
          title: 'Get Results',
          description: 'People take your quiz and you see the results.',
        },
      ],
    },
    cta: {
      title: 'Ready to create your first quiz?',
      description: 'Join thousands of creators who are already using QuizFlow.',
      button: 'Get Started Free',
    },
    preview: {
      logo_suffix: 'Flow',
      question_label: 'Questions',
      question_added: '1 Question added',
      question_item: 'Question 1',
      answer_options: 'Answer options',
      option_one: 'Option 1',
      option_two: 'Option 2',
      easy_to_create: 'Easy to create!',
      mock_question_text: 'Enter question text',
      sidebar: {
        all_quizzes: 'All Quizzes',
        my_quizzes: 'My Quizzes',
        create_quiz: 'Create Quiz',
        results: 'Results',
        create_quiz_description: 'Start a new quiz',
      },
    },
  },
  create: {
    base: {
      section_title: 'Basic Information',
      question_section_title: 'Questions',
      question_section_subtitle: 'questions added',
      question_tips: 'Drag questions to reorder them. ',
      title: {
        label: 'Quiz Title',
        placeholder: 'Enter quiz title',
      },
      description: {
        label: 'Description',
        placeholder: 'Add a short description...',
      },
      difficulty: {
        label: 'Difficulty',
        placeholder: 'Select difficulty',
      },
      category: {
        label: 'Category',
        placeholder: 'Add category...',
        create_new: (name: string) => `Create "${name}"`,
      },
    },
    questions: {
      title: 'Questions',
      subtitle: 'questions added',
      item: 'Question',
      q_text: 'Question text',
      q_text_placeholder: 'Enter question text',
      a_options: 'Answer options',
      a_options_placeholder: 'Enter answer options',
      explanation: 'Explanation(optional)',
      explanation_placeholder: 'Enter explanation(optional)',
      options_empty_text: 'Add more than 1 option',
    },
    buttons: {
      add_question: 'Add Question',
      add_option: 'Add Option',
      save: 'Publish Quiz',
      patch: 'Update Quiz',
      draft: 'Save Draft',
      collapse: 'Collapse all',
    },
    messages: {
      quiz_id_required_for_update: 'Quiz id is required for update.',
      failed_to_update: 'Failed to update quiz. Please try again.',
      failed_to_create: 'Failed to create quiz. Please try again.',
      quiz_data_valid: 'Quiz data is valid.',
    },
    validation: {
      answer_text_required: 'Answer text is required.',
      question_text_required: 'Question text is required.',
      at_least_two_answers: 'Each question must have at least two answers.',
      one_correct_answer: 'Each question must have one correct answer.',
      title_required: 'Title is required.',
      description_required: 'Description is required.',
      select_at_least_one_category: 'Select at least one category.',
      difficulty_required: 'Difficulty is required.',
      add_at_least_one_question: 'Add at least one question.',
    },
  },
  quiz_list: {
    search_placeholder: 'Search quizzes...',
    menu: {
      make_draft: 'Make it draft',
      make_published: 'Make it published',
      duplicate: 'Duplicate',
      delete: 'Delete',
    },
    item: {
      unknown_author: 'Unknown',
      meta: (questionsCount: number, authorName: string) =>
        `${questionsCount} Questions • By ${authorName}`,
      start_quiz: 'Start Quiz',
      edit: 'Edit',
      preview: 'Preview',
    },
  },
  preview: {
    question_count: (count: number) => `${count} Questions`,
    previous: 'Previous',
    next: 'Next',
    submit: 'Submit',
    submit_disabled_tip: 'Submit button is disabled due to preview mode',
    question_title: (index: number) => `Question ${index}`,
  },
  shared: {
    logo_alt: 'Quiz Flow logo',
    user_menu: {
      settings: 'Settings',
      log_out: 'Log Out',
    },
    mobile_topbar_icon_placeholder: 'some-icon',
  },
  api: {
    difficulty_expected_array: 'Expected an array of difficulty values.',
    invalid_quiz_payload: 'Invalid quiz payload.',
    unable_seed_difficulties: 'Unable to seed difficulties.',
    unable_create_quiz: 'Unable to create quiz.',
  },
  shared_quiz: {
    cta: {
      title: 'Create your own quiz',
      product: 'QuizFlow',
      icon: ExternalLink,
    },
    top: {
      Questions: 'Questions',
      Question: 'Question',
      of: 'of',
      Quiz_Progress: 'Quiz Progress',
      Categories: 'Categories',
      Difficulty: 'Difficulty',
      Description: 'Description',
    },
    labels: {
      difficulty: 'Difficulty:',
      categories: 'Categories:',
    },
    progress: {
      Answered: 'Answered',
      Current: 'Current',
      Unanswered: 'Unanswered',
    },
    tips: {
      about: 'About this quiz',
      tips: [
        'This quiz is created by a QuizFlow user.',
        'Want to create your own quiz like this?',
      ],
      button: {
        text: 'Create Your Quiz',
        icon: ExternalLink,
      },
    },
    registration_not_required: {
      icon: CheckCircle,
      title: 'No registration required',
      description:
        'You can take this quiz without registering.  You can close this page after submitting your answers.',
    },
    buttons: {
      submit: 'Submit Answers',
      next: 'Next Question',
      previous: 'Previous Question',
    },
  },
};
